# Generated by Django 4.2 on 2025-05-13 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cod_area", models.CharField(max_length=5)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                (
                    "estado_respuesta",
                    models.CharField(
                        choices=[
                            ("Contestada", "Contestada"),
                            ("No Contestada", "No Contestada"),
                            ("En Proceso", "En Proceso"),
                        ],
                        default="No Contestada",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_contacto",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.TextField()),
                (
                    "fecha_respuesta",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacto.consulta",
                    ),
                ),
            ],
        ),
    ]
