# Generated by Django 4.2 on 2025-05-30 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datousuario",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="datousuario",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="datousuario",
            name="usuario",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
