# Generated by Django 4.2 on 2025-04-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("No activo", "No activo")],
                        default="No activo",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("stock", models.IntegerField(blank=True, null=True)),
                (
                    "fecha_publicacion",
                    models.DateTimeField(verbose_name="Fecha de publicación"),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("No activo", "No activo")],
                        max_length=10,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos/%Y/%m/%d"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="productos.categoria",
                    ),
                ),
            ],
        ),
    ]
