# Generated by Django 4.2 on 2025-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_imgproducto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imgproducto",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("No activo", "No activo")],
                default="No Activo",
                max_length=10,
            ),
        ),
    ]
