"""
Django settings for ascensores project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path
import os
from dotenv import load_dotenv

# Carga las variables del archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zo)tlo*ahi&d%0yssf!u2(^ufkxt6!$ad$)u@_38$8a@y@t)sb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Apps por defecto
    'django.contrib.sites',
    'registration', #should be immediately above 'django.contrib.admin'
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "restapi.apps.RestapiConfig",
    "rest_framework",
    'django.contrib.sitemaps',
    # Apps de terceros
    "captcha",
    'ckeditor',
    'ckeditor_uploader', # Permite subir archivos a CKEditor
    'simple_history',
    'sendgrid_backend',

    # Mis Apps
    "bienvenida.apps.BienvenidaConfig",
    "productos.apps.ProductosConfig",
    "usuarios.apps.UsuariosConfig",
    "contacto.apps.ContactoConfig",
    "carro.apps.CarroConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = "ascensores.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join (BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ascensores.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ('es', 'Spanish'),
    ('en', 'English'),  # Si también quieres soporte para inglés
    # Agrega otros idiomas que necesites
]

LANGUAGE_CODE = 'es'  # Establece el idioma por defecto a español

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static_dev"),)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ACCOUNT_ACTIVATION_DAYS = 7 # Este es el número de días que los usuarios tendrán para activar sus cuentas después de registrarse..
REGISTRATION_AUTO_LOGIN = True  
"""REGISTRATION_AUTO_LOGIN: Opcional. Si es Verdadero, los usuarios iniciarán sesión automáticamentecuando hagan clic
en el enlace de activación que aparece en su correo electrónico. El valor predeterminado es Falso."""
SITE_ID = 1 # SITE_ID = 1, estás diciendo que este es el sitio principal o predeterminado que tu aplicación utilizará.

LOGIN_REDIRECT_URL = "/" # Define a qué vista voy luego del logueo.
LOGIN_URL = "django.contrib.auth.views.login" # Define la URL de la vista que maneja el proceso de inicio de sesión.

# CKEDITOR
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "uploads/"

#########################
#CONFIGURACIÓN DE E-MAIL:
#########################

# Configuración de email según entorno
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

DEFAULT_FROM_EMAIL = 'nicolassalvay.claro@gmail.com'

#EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY')
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")

if not SENDGRID_API_KEY and EMAIL_BACKEND == "sendgrid_backend.SendgridBackend":
    raise ImproperlyConfigured("SENDGRID_API_KEY no se encontró en el entorno.")