# Generated by Django 4.2 on 2025-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("stock", models.IntegerField()),
                (
                    "fecha_publicacion",
                    models.DateTimeField(verbose_name="Fecha de publicación"),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "estado",
                    models.CharField(
                        choices=[("D", "Disponible"), ("ND", "No disponible")],
                        max_length=2,
                    ),
                ),
                ("imagen", models.ImageField(upload_to="productos/")),
            ],
        ),
    ]
