# Generated by Django 4.2 on 2025-03-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bienvenida", "0002_categoria_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="bienvenida.categoria",
            ),
        ),
    ]
