# Generated by Django 4.2 on 2025-03-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bienvenida", "0003_alter_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("NA", "No activo")],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("ND", "No activo")], max_length=2
            ),
        ),
    ]
