# Generated by Django 4.2 on 2025-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bienvenida", "0004_categoria_estado_alter_producto_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("No activo", "No activo")],
                default="No activo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("No activo", "No activo")],
                max_length=10,
            ),
        ),
    ]
